## This function creates a special "matrix" object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
        # Note: x must be an invertible, square matrix
        
        mat <- NULL
        set <- function(y) {
                
                # Set x and mat to makeCacheMatrix environment
                x <<- y
                mat <<- NULL
        }
        
        # Generate additional getters/setters for cacheSolve function
        get <- function() x
        setinverse <- function(inverse) mat <<- inverse
        getinverse <- function() mat
        
        # Name getters/setters
        list(set = set, 
             get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## This function computes the inverse of the special "matrix" returned 
## by makeCacheMatrix above. If the inverse has already been calculated 
## (and the matrix has not changed), then the cachesolve should retrieve 
## the inverse from the cache.

cacheSolve <- function(x, ...) {
        # Note: x must be generated by makeCacheMatrix
        # Displays inverse of x, either from memory or calculated
        
        # Retrieve currently stored inverse value
        mat <- x$getinverse()
        
        # Check if inverse is null, print if it is not
        if(!is.null(mat)) {
                message("Retieving Cached Data...")
                return(mat)
        }
        
        # Calculate inverse if not in memory
        temp <- x$get()
        mat <- solve(temp, ...)
        x$setinverse(mat)
        mat
}
